# Use Rocky Linux Minimal (lightweight, CentOS-like)
FROM rockylinux:9-minimal
# Set the working directory in the container
WORKDIR /opt
# Install dependencies (microdnf is faster/lighter than yum)
RUN microdnf install wget tar gzip -y && microdnf clean all
RUN wget -O splunk-10.2.0-d749cb17ea65-linux-amd64.tgz "https://download.splunk.com/products/splunk/releases/10.2.0/linux/splunk-10.2.0-d749cb17ea65-linux-amd64.tgz"
RUN tar -xvzf splunk-10.2.0-d749cb17ea65-linux-amd64.tgz
RUN rm -rf splunk-10.2.0-d749cb17ea65-linux-amd64.tgz
  
# Expose ports
EXPOSE 8000 8089
