# Use Rocky Linux Minimal (lightweight, CentOS-like)
FROM rockylinux:9-minimal
# Set the working directory in the container
WORKDIR /opt
# Install dependencies (microdnf is faster/lighter than yum)
RUN microdnf install wget tar gzip -y && microdnf clean all
RUN wget -O splunk-9.4.5-8fb2a6c586a5-linux-amd64.tgz "https://download.splunk.com/products/splunk/releases/9.4.5/linux/splunk-9.4.5-8fb2a6c586a5-linux-amd64.tgz"
RUN tar -xvzf splunk-9.4.5-8fb2a6c586a5-linux-amd64.tgz
RUN rm -rf splunk-9.4.5-8fb2a6c586a5-linux-amd64.tgz
  
# Expose ports
EXPOSE 8000 8089
