# Use an official CentOS runtime as the base image
FROM centos:latest

# Set the working directory in the container
WORKDIR /opt

# Install dependencies
RUN cd /etc/yum.repos.d/ && \
    sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* && \
    yum install wget -y

# Download and extract Splunk
ARG SPLUNK_URL
ARG SPLUNK_FILE
RUN wget -O ${SPLUNK_FILE} ${SPLUNK_URL} && \
    tar -xvzf ${SPLUNK_FILE} && \
    rm ${SPLUNK_FILE}

# Expose necessary ports
EXPOSE 8000 8089

# Usage
# docker build --build-arg SPLUNK_URL="https://download.splunk.com/products/splunk/releases/8.1.10/linux/splunk-8.1.10-c7993e64d7f2-Linux-x86_64.tgz" --build-arg SPLUNK_FILE="splunk-8.1.10-c7993e64d7f2-Linux-x86_64.tgz" -t splunk-centos:8.1.10.
