
# Use an official Node.js runtime as the base image
FROM node:current-buster-slim

# Set the working directory in the container
WORKDIR /opt

# Install necessary dependencies
RUN apt-get update && \
    apt-get install -y wget && \
    rm -rf /var/lib/apt/lists/*

# Download and extract Splunk
RUN wget -O splunk-9.2.0.1-d8ae995bf219-Linux-x86_64.tgz "https://download.splunk.com/products/splunk/releases/9.2.0.1/linux/splunk-9.2.0.1-d8ae995bf219-Linux-x86_64.tgz" && \
    tar -xvzf splunk-9.2.0.1-d8ae995bf219-Linux-x86_64.tgz && \
    rm splunk-9.2.0.1-d8ae995bf219-Linux-x86_64.tgz

# Expose necessary ports
EXPOSE 8000 8089

